# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      -   id: blacken-docs
          additional_dependencies:
              - black==23.7.0
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.7.10
          - flake8-no-pep420==2.7.0
          - flake8-print==5.0.0
          - flake8-comprehensions==3.14.0
- repo: https://github.com/rtts/djhtml
  rev: '3.0.6'
  hooks:
    - id: djhtml
      args:
        - --tabwidth=2
    - id: djcss
    - id: djjs
