run:
	@poetry run python manage.py runserver_plus

mm:
	@poetry run python manage.py makemigrations

mi:
	@poetry run python manage.py migrate

shell:
	@poetry run python manage.py shell_plus

su:
	@poetry run python manage.py createsuperuser
